version: '3.8'
services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb             # 👈 nombre correcto del contenedor (usado en deploy.yml)
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fadic123
      MYSQL_DATABASE: laboratorio_bd
      MYSQL_USER: laboratorio
      MYSQL_PASSWORD: fadic123
    ports:
      - "3306:3306"
    volumes:
      - ./docker/estructura.sql:/docker-entrypoint-initdb.d/estructura.sql  # 👈 ejecuta al inicio

  app:
    build: .
    container_name: laboratorio_app      # 👈 nombre real del contenedor de app (corrige en deploy.yml)
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/laboratorio_bd
      SPRING_DATASOURCE_USERNAME: laboratorio
      SPRING_DATASOURCE_PASSWORD: fadic123
