name: Deploy Lab Clinico Locally

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_PROJECT_NAME: 'labapp'
  APP_CONTAINER_NAME: 'laboratorio_app'       # Nombre del contenedor de la app
  DB_CONTAINER_NAME: 'mariadb'                # Nombre del contenedor de la base de datos
  DB_NAME: 'laboratorio_bd'
  DB_USER: 'laboratorio'
  DB_PASSWORD: 'fadic123'

jobs:
  build-and-deploy:
    name: Build and Deploy Lab Clinico
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy with Docker Compose
        run: |
          echo "🚀 Despliegue de Lab Clínico iniciando..."

          echo "🔎 Verificando arquitectura del runner..."
          uname -m

          cd .

          echo "🧹 Deteniendo cualquier despliegue anterior..."
          docker-compose -p ${{ env.DOCKER_PROJECT_NAME }} down -v --remove-orphans || echo "⚠ No se encontró despliegue previo."

          echo "🏗 Levantando nueva versión..."
          docker-compose -p ${{ env.DOCKER_PROJECT_NAME }} up -d --build

          echo "⏳ Esperando 30 segundos a que la DB se estabilice..."
          sleep 30

          echo "💾 Ejecutando script SQL si es necesario..."
          docker exec -i ${{ env.DB_CONTAINER_NAME }} mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} ${{ env.DB_NAME }} < ./docker/estructura.sql || echo "⚠ No se pudo ejecutar el script SQL"

          echo "🧾 Logs de la base de datos:"
          docker logs --tail 50 ${{ env.DB_CONTAINER_NAME }}

          echo "📦 Verificando si el contenedor de la app está corriendo..."
          APP_STATUS=$(docker inspect -f '{{.State.Running}}' ${{ env.APP_CONTAINER_NAME }} 2>/dev/null || echo "false")
          if [ "$APP_STATUS" != "true" ]; then
            echo "❌ El contenedor de la app no está corriendo. Verifica errores en el log."
            docker logs ${{ env.APP_CONTAINER_NAME }}
            exit 1
          fi

          echo "📋 Estado actual de los contenedores:"
          docker-compose -p ${{ env.DOCKER_PROJECT_NAME }} ps

          echo "📝 Logs recientes de la aplicación:"
          docker logs --tail 100 ${{ env.APP_CONTAINER_NAME }}

          echo "✅ Despliegue completo."
